### ISSUE TITLE
Sending lambda from local sites to remote doesn't make sense

### ISSUE THREAD

**Issue by hvgazula** [trendscenter/coinstac-regression-fsl#8]
The lambda is a value entered in the UI and is used at the remote site only (in this computation). So, sending this lambda to local and then back to remote doesn't make sense. Discuss with @rssk about this.

**Comment by hvgazula** [comment]
@rssk Is it possible to make values from the UI (at the time of computation creation) available at the remote directly, without having to route it from the local?

**Comment by rssk** [comment]
its an interesting question, right now no, but the reason is a little complicated. Basically the remote does a 'noop' for a round waiting for the locals, and in doing this discards the initial input that has the partially fulfilled 'inputspec' the locals use, so those initial values arent present when the remote actually executes

The reason why it works like this is historical and not really for any real reason but its a limitation, however it might be possible to put that information aside to give to the remote when it actually starts on its 'initial' iteration.  I think it's likely look like this dict wise:

```
{
  lamda: 1
  otherThing: 2
  local0: {}
  local1:{}
  ....
}
```

however this would have the downside of breaking how sites are likely iterated for data on the remote, so its not so simple to implement without issues

**Comment by hvgazula** [comment]
I see. Good to know. I'll close this issue then.
